#!/bin/bash
LOG_URL=${SIM_BASE_URL}/well/${SIM_UID_WELL}/wellbore/${SIM_UID_WELL}-wb1/log/${SIM_UID_TIME_LOG}
ruby -I. run_timelog.rb --url "$LOG_URL"  --log "$SIM_TIME_LOG_FILE"  -u $SIM_USERNAME -p $SIM_PASSWORD

