export SIM_BASE_URL="https://artemis:8443/witsml/repository"
#export SIM_UID_WELL="42-177-32094-00-00"
export SIM_UID_WELL="LIVE-42-177-32094-00-00"
export SIM_UID_TIME_LOG="LIVE-L-499007-Time"
export SIM_NAME_WELL="LIVE KOENNING UNIT"
export SIM_NAME_TIME_LOG="LIVE-TIMELOG"
export SIM_WELL_FILE=./data/well.witsml
export SIM_WELLBORE_FILE=./data/wellbore.witsml
export SIM_TIME_LOG_FILE=./data/time-log.witsml
export SIM_USERNAME=admin
export SIM_PASSWORD=admin